version: "3.7"

services:
  todo-server:
    build: ./todo-server
    ports:
      - 8081:8080
    environment:
      DB_HOST: mysql
      DB_PORT: 6603
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: todos
  mysql:
    ports:
      - 6603:3306
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
